apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: ${SERVICE_NAME}-store
  namespace: ${K8S_NAMESPACE}
  labels:
    app.kubernetes.io/part-of: microservice-platform
    app.kubernetes.io/managed-by: kustomize
spec:
  provider:
    aws:
      service: SecretsManager
      region: ${AWS_REGION}
      auth:
        jwt:
          serviceAccountRef:
            name: ${SERVICE_NAME}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ${SERVICE_NAME}-secrets
  namespace: ${K8S_NAMESPACE}
  labels:
    app.kubernetes.io/part-of: microservice-platform
    app.kubernetes.io/managed-by: kustomize
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: ${SERVICE_NAME}-store
    kind: SecretStore
  target:
    name: ${SERVICE_NAME}-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        key: platform/${ENVIRONMENT}/${SERVICE_NAME}
