apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ${SERVICE_NAME}
  namespace: ${K8S_NAMESPACE}
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: microservice-platform
    app.kubernetes.io/name: ${SERVICE_NAME}
    app.kubernetes.io/instance: ${SERVICE_NAME}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: ${SERVICE_NAME}

  policyTypes:
    - Ingress
    - Egress

  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/instance: ${SERVICE_NAME}
      ports:
        - protocol: TCP
          port: ${CONTAINER_PORT}

    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: ingress-controller
      ports:
        - protocol: TCP
          port: ${CONTAINER_PORT}

  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/instance: ${SERVICE_NAME}

    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53

    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 5353
        - protocol: TCP
          port: 5353
