apiVersion: v1
kind: Service

metadata:
  name: ${SERVICE_NAME}
  namespace: ${K8S_NAMESPACE}

  labels:
    app: ${SERVICE_NAME}

spec:
  type: ${SERVICE_TYPE}

  selector:
    app: ${SERVICE_NAME}

  ports:
    - name: http
      port: ${SERVICE_PORT}
      targetPort: ${CONTAINER_PORT}
      protocol: TCP
